/*
 * @(#)PromptSearchDemo.java
 *
 * $Date: 2015-02-28 21:59:45 +0100 (Sa, 28 Feb 2015) $
 *
 * Copyright (c) 2011 by Jeremy Wood.
 * All rights reserved.
 *
 * The copyright of this software is owned by Jeremy Wood. 
 * You may not use, copy or modify this software, except in  
 * accordance with the license agreement you entered into with  
 * Jeremy Wood. For details see accompanying license terms.
 * 
 * This software is probably, but not necessarily, discussed here:
 * https://javagraphics.java.net/
 * 
 * That site should also contain the most recent official version
 * of this software.  (See the SVN repository for more details.)
 */
package com.bric.swing;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

import com.bric.blog.Blurb;
import com.bric.blog.ResourceSample;
import com.bric.plaf.RoundTextFieldUI;

/** A demo applet featuring a prompt for text fields, and a UI for
 * text fields with round rects.
 * 
 * 
 * <!-- ======== START OF AUTOGENERATED SAMPLES ======== -->
 * <p><img src="https://javagraphics.java.net/resources/samples/PromptSearchDemo/sample.png" alt="new&#160;com.bric.swing.PromptSearchDemo()">
 * <!-- ======== END OF AUTOGENERATED SAMPLES ======== -->
 */
@Blurb (
filename = "PromptSearch",
title = "Text: Prompts and Search Fields",
releaseDate = "December 2009",
summary = "This article has 2 goals:\n"+
"<br>1. Display a gray prompt over a <code>JTextField</code> if it doesn't have the focus.</br>\n"+
"<br>2. Implement a <code><a href=\"https://javagraphics.java.net/doc/com/bric/plaf/RoundTextFieldUI.html\">"+
"RoundTextFieldUI</a></code> (with an optional magnifying glass).</br>",
instructions = "This applet provides a simple demonstration of text field prompts and a search field UI.",
link = "http://javagraphics.blogspot.com/2009/12/text-prompts-and-search-fields.html",
sandboxDemo = true
)
@ResourceSample( sample="new com.bric.swing.PromptSearchDemo()" )
public class PromptSearchDemo extends BricApplet {
	private static final long serialVersionUID = 1L;
	
	public static void main(String[] args) {
		JFrame f = new JFrame();
		f.getContentPane().add(new PromptSearchDemo());
		f.pack();
		f.setVisible(true);
		f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}
	
	JTextField plainField = new JTextField("",10);
	JTextField roundField = new JTextField("",10);
	JTextField roundSearchField = new JTextField("",10);
	
	public PromptSearchDemo() {
		getContentPane().setLayout(new GridBagLayout());
		GridBagConstraints c = new GridBagConstraints();
		c.gridx = 0; c.gridy = 0;
		c.anchor = GridBagConstraints.EAST;
		c.weightx = 1; c.weighty = 0;
		c.insets = new Insets(5,5,5,5);
		getContentPane().add(new JLabel("Plain:"),c);
		c.gridy++;
		getContentPane().add(new JLabel("Rounded:"),c);
		c.gridy++;
		getContentPane().add(new JLabel("Search:"),c);
		c.gridx++; c.gridy = 0;
		c.anchor = GridBagConstraints.WEST; c.weightx = 1;
		c.fill = GridBagConstraints.BOTH;
		getContentPane().add(plainField,c);
		c.gridy++;
		getContentPane().add(roundField,c);
		c.gridy++;
		getContentPane().add(roundSearchField,c);
		
		roundField.setUI(new RoundTextFieldUI());
		roundSearchField.setUI(new RoundTextFieldUI());
		
		new TextFieldPrompt(plainField,"Prompt");
		new TextFieldPrompt(roundField,"Search #1");
		new TextFieldPrompt(roundSearchField,"Search #2");
		roundSearchField.putClientProperty("useSearchIcon", Boolean.TRUE);
		
		getContentPane().setBackground(Color.white);
	}
}
