/*
 * @(#)FilledButtonUIDemo.java
 *
 * $Date: 2015-02-28 21:59:45 +0100 (Sa, 28 Feb 2015) $
 *
 * Copyright (c) 2011 by Jeremy Wood.
 * All rights reserved.
 *
 * The copyright of this software is owned by Jeremy Wood. 
 * You may not use, copy or modify this software, except in  
 * accordance with the license agreement you entered into with  
 * Jeremy Wood. For details see accompanying license terms.
 * 
 * This software is probably, but not necessarily, discussed here:
 * https://javagraphics.java.net/
 * 
 * That site should also contain the most recent official version
 * of this software.  (See the SVN repository for more details.)
 */
package com.bric.plaf;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.plaf.ComponentUI;

import com.bric.blog.Blurb;
import com.bric.blog.ResourceSample;

/** A simple demo of different {@link FilledButtonUI} samples.
 * 
 * 
 * <!-- ======== START OF AUTOGENERATED SAMPLES ======== -->
 * <p><img src="https://javagraphics.java.net/resources/samples/FilledButtonUIDemo/sample.png" alt="new&#160;com.bric.plaf.FilledButtonUIDemo()">
 * <!-- ======== END OF AUTOGENERATED SAMPLES ======== -->
 */
@Blurb (
filename = "FilledButtonUI",
title = "Buttons: New UIs",
releaseDate = "August 2009",
summary = "Sure the buttons in <a href=\"http://developer.apple.com/mac/library/technotes/tn2007/tn2196.html#BUTTONS\">Apple's Tech Note 2196</a> "+
"are great, but they're so... black-box-ish. And they're only available on Macs.\n"+
"<p>This article sets up a <a href=\"https://javagraphics.java.net/doc/com/bric/plaf/FilledButtonUI.html\">new framework</a> for "+
"<code>ButtonUIs</code>, and provides around 10 UI's to choose from. "+
"(But you can make more if you want to...) Also each <code>ButtonUI</code> can be turned into a <code>ComboBoxUI</code>.",
instructions = "This applet demonstrates several new button UIs. Select a UI in the list on the left, "+
"and interact with the the UIs on the right.",
link = "http://javagraphics.blogspot.com/2009/08/buttons-new-uis.html",
sandboxDemo = true
)
@ResourceSample( sample="new com.bric.plaf.FilledButtonUIDemo()" )
public class FilledButtonUIDemo extends UIDemo {
	private static final long serialVersionUID = 1L;
	
	public static void main(String[] args) {
		SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				try {
					String lf = UIManager.getSystemLookAndFeelClassName();
					UIManager.setLookAndFeel(lf);
				} catch (Throwable e) {
					e.printStackTrace();
				}
				
				
				JFrame f = new JFrame("Button UIs");
				f.getContentPane().add(new FilledButtonUIDemo());
				f.pack();
				f.setVisible(true);
				f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
			}
		});
	}
	
	public FilledButtonUIDemo() {
		super(new ComponentUI[] {
				new BevelButtonUI(),
				new CapsuleButtonUI(),
				new GradientButtonUI(),
				new PlasticButtonUI(),
				new RecessedButtonUI(),
				new RetroButtonUI(),
				new RoundRectButtonUI(),
				new SquareButtonUI(),
				new TexturedButtonUI(),
				new VistaButtonUI(),
				new XPButtonUI(),
				new XPSubtleButtonUI()
		}, new FilledButtonUIHandler() );
	}
}
